# Exercise Background

This small application based coding exercise is ment to expose you to the use of the numpy library as well as give you a taste of tasks that you might be needed to perform during machine learning. 

Usually, machine learning involves working on large data sets. This notebook will walk you through normalising the data and then dividing the data set into smaller subsets. It is recommended that while attempting each of the tasks visit the NumPy library to find the most appropriate function which can help you achieve the desired result. More often than not you will find the functions which you require prewritten in the library. The **numpy library** can be found [here.](https://numpy.org/doc/stable/) 

Without further ado, the first task is to mean normalise a data set. Mean normalising is a data transformation done to reduce the variations in the data set. For example, consider a data set which has integers between 0 and 10000. That is a lot of variation, and it becomes difficult to build ML algorithms on this data. So mean normalisation is done on such data, after the transformation, the mean of the data will be zero, and standard deviation will be 1.  Even though the actual values of data will change a lot, but the overall variation is still kept intact. If the concept of normalisation feels a bit unclear dont worry all of this will be covered in the future sections of this program. For now, let’s concentrate on the tasks at hand. 


# Task 1: Mean Normalisation: 

**Question 1.1** Create a 2D of random integers between 0 and 10,000 (including both 0 and 10,000) with 25000 rows and 15 columns. This will be the dataset you will use in the notebook. 

In [29]:
# import NumPy into Python
import numpy as np

# Create a 25000 x 15 ndarray with random integers in the interval [0, 10000].

X = np.random.randint(0, 10001, (25000, 15))

# print the shape of X

print(X.shape)

(25000, 15)


In [30]:
# print the first row of X

X[1]

array([  87, 9568, 2429, 8806, 3575, 8288, 4001, 6842, 1221, 6135, 5885,
       5043, 9690, 1303, 7447])

Now that you created the array we will mean normalize it. The equation for normalisaing the data is given below:

$\mbox{Norm_Col}_i = \frac{\mbox{Col}_i - \mu_i}{\sigma_i}$

where $\mbox{Col}_i$ is the $i$th column of $X$, $\mu_i$ is average of the values in the $i$th column of $X$, and $\sigma_i$ is the standard deviation of the values in the $i$th column of $X$. To put it simply, to find the new value of each element, you have to subtract the mean of respective column form that value and divide the result with the standard deviation of that columns. Now the question is, Why are these operations being done column-wise? That is because usually all the procedures in ML are done column-wise. So it will be beneficial for us to develop the habit of thinking about data column-wise.   

**Question 1.2** Find the mean and the standard deviation of each of the columns in the dataset. The result will be two 1D arrays with 15 elements each, representing the mean and standard deviation for each of the columns in the dataset.  

In [31]:
# Average of the values in each column of X

ave_cols = np.mean(X, axis = 0)


# print ave_cols  

print(ave_cols)

# Standard Deviation of the values in each column of X

std_cols = np.std(X, axis = 0)

print(std_cols)

# print std_cols  


[4980.75944 4994.3912  5004.4294  5021.399   4999.84396 4999.226
 4976.49932 4955.313   5007.10748 4987.16912 4978.2804  4982.17552
 5016.45396 5003.38352 4995.06404]
[2890.28539938 2877.781996   2879.76518494 2882.10417823 2894.19290777
 2878.47253529 2894.03926152 2885.88940384 2884.12076194 2890.61321694
 2886.7469512  2883.64923845 2889.67681817 2879.07670082 2891.50059228]


**Question 1.3** Print the shape of each both the arrays, they should have 15 elements each.  

In [32]:
# Print the shape of ave_cols
len(ave_cols)
# Print the shape of std_cols
len(std_cols)

15

**Question 1.4** Now that you have mean and standard deviation calculated, it is time to apply the transformation to the dataset. 
 
**HINT** The broadcast property of NumPy can make this a lot easier. You can read about it [here](https://numpy.org/doc/stable/user/basics.broadcasting.html).
All you have to do is create one row of transformation values and repeat them through all the values.

In [33]:
# Mean normalize X

X_norm = (X - ave_cols)/std_cols

**Question 1.5** If the transformation has been performed correctly, the mean of elements in each column will be approximately 0. Also, the average of the **minimum** value in each column of X_norm and the average of the **maximum** value in each column of X_norm will have almost the same face value with opposite signs. Let’s confirm if the transformation has happened correctly. 

In [37]:
# Print the average of all the values of X_norm

print(np.mean(X_norm))

# Print the average of the minimum value in each column of X_norm


print(np.mean(np.min(X_norm, axis = 0)))

# Print the average of the maximum value in each column of X_norm

print(np.mean(np.max(X_norm, axis = 0)))




2.3230010507783542e-17
-1.7302494703888627
1.7348408282326582


Be mindful that the exact values might not match since the dataset was initialized using the random function. 

# Data Spliting 

After data processing, it is a regular practice in ML to split the dataset into three datasets. 

1. A Training Set
2. A Cross Validation Set
3. A Test Set

The ratios in which the data is split varies a bit from case to case. But the accepted standard 6:2:2 for train, test, and validation respectively. That is 60% for training data and so on. Again why is the data split or what is the signification of these smaller data sets? These questions are better left unanswered for now. 
The tanks assigned to you is to split the data in the given proportions randomly. 
For instance, if the data set had ten elements, this is how you would do it. 

In [11]:
# We create a random permutation of integers 0 to 9
np.random.permutation(10)

array([8, 3, 7, 5, 2, 6, 1, 9, 0, 4])

1. training set = 8,3,7,5,2,6
2. Cross Validation Set = 1,9
3. Test Set = 0,4

**Question 2.1** Similarly, create a 1D array representing the indexes of the rows in the dataset X_norm. U can use the   `np.random.permutation()` function for randomising the indexes. 

In [53]:
# Create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm `

# X_norm.shape # has 25000 rows 

row_indices = np.random.permutation(np.arange(0,25000)) # gives a 1 d array, sabai rows ko indices haru bata permutation garera euta 1d array
                                          # dine jun ma indices haru hun6 sab X_norm ko row indices haruko
row_indices

array([ 5695,  6467,  4549, ...,  8785, 21540, 22402])

In [54]:
# Print the shape of row_indices
row_indices.shape

(25000,)

**Question 2.2** Split the row indexes in the needed proportions. You can use the slicing methods you have learnt in this session to make the job easier.  

In [69]:
# Make any necessary calculations.
# You can save your calculations into variables to use later.
train = row_indices[:15000]
test = row_indices[15000:20000]
val  = row_indices[20000:]

# type(train)
# train
# print(train)
print(train.shape)
print(test.shape)
print(val.shape)

(15000,)
(5000,)
(5000,)


**Question 2.3** Now make use of the indexes that you made to split the data also similarly once the data is split print the shape of each of the smaller data sets. `X_train` should have 15000 rows and 15 columns. `X_test` should have 5000 rows and 15 columns. `X_val` should have 5000 rows and 15 columns. 

In [91]:
rra = np.random.random((10,4))
rra.shape # 10 rows cha

rra[[2,4,5]] # index haru ya llist of indexes haru duwai pass garna mil6

# aba 10 row indices bata permutation nikalne
# indices_list= np.random.permutation(10)
# indices_list

# train_split = indices_list[:6]
# cross_val_split = indices_list[6:8]
# test_split = indices_list[8:]

# xTrain = rra[train_split]
# xCrossVal = rra[cross_val_split]
# xTest = rra[test_split]

array([[0.07801959, 0.22072533, 0.0697668 , 0.3571946 ],
       [0.66772143, 0.60970506, 0.66008417, 0.20815214],
       [0.86947961, 0.66536056, 0.41720904, 0.53619167]])

In [80]:
print(train)
print(val)
print(test)

# Create a Training Set
# aba list of indices dera X_norm bata values haru sab lai euta variable ma halne

X_train = X_norm[train] 
X_train

# Create a Cross Validation Set
cross_val = X_norm[val]
cross_val

# Create a Test Set
X_test = X_norm[test]
X_test

[ 5695  6467  4549 ...  9287 11037   174]
[23893 21811  4324 ...  8785 21540 22402]
[21707  1841 17528 ...  7716 15927 19318]


array([[-0.57425451, -1.14337751,  0.30612586, ...,  0.2081707 ,
         0.93488877, -0.3707639 ],
       [ 1.52173227,  0.59754658,  1.63574816, ...,  0.71722416,
        -0.44541485, -0.4572242 ],
       [ 0.13432603, -1.10028877, -1.57701379, ..., -1.17053019,
        -0.80004243, -0.44788649],
       ...,
       [-1.63401145,  0.81194781, -0.20954118, ..., -1.52904779,
         0.82200536, -1.02509543],
       [ 0.63912047, -1.43700642, -1.18600969, ..., -0.61925747,
        -0.69584236,  0.40772461],
       [-0.88668041, -0.59573352, -0.89709724, ...,  1.37473714,
        -0.73474372, -0.54783459]])

In [92]:
# Print the shape of X_train

print(X_train.shape)

# Print the shape of X_crossVal

print(cross_val.shape)

# Print the shape of X_test

print(X_test.shape)

(15000, 15)
(5000, 15)
(5000, 15)
